### ISSUE TITLE
Non-developers conduct usability tests

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#107] opened 2020-02-27 17:28 UTC
It would be good to have non-developers exercise some common use-case scenarios to make sure a) it can be done; b) it can be done by those that are not the experts; c) the documentation is adequate. Some examples of common use cases are: 

- All resolutions 
- Format: NEMSIO and GRIB2
- Source of GRIB2: dates in ftp bundle, dates from NOMADS, GRIB2 available somewhere else for period Jan2 018 to Feb 2019
- Make sure format changes above trigger the NSST or non-SST suites and appropriate namelists
- Stochastics on/off (all on or all off: SHUM, SKEB, and SPPT)
- Change a namelist option for the model (e.g., ccn_l)
- Make plots to evaluate results

I propose we save this for post-release: Change what fields are output from UPP.

I have put this proposal in @pjpegion [Test Plan spreadsheet](https://docs.google.com/spreadsheets/d/1eD5pnPf8g_-atyR7r2hlKyHSyhOC95M28qKU8Jls_-c/edit#gid=0). @rsdunlapiv @jedwards4b @uturuncoglu 

We have some people in DTC trying to work through some of this, but would it be a good idea to email the original testing team and ask if besides helping with the test plan they are available to conduct some tests?

**Comment by rsdunlapiv** [comment] 2020-02-27 17:44
@ligiabernardet would it be possible to begin assigning these different configurations to any people who have been identified to help with testing - and list those assignments on the spreadsheet?

**Comment by pjpegion** [comment] 2020-02-27 17:56
@ligiabernardet and @rsdunlapiv I am working for a willing tester in my group to do these tests on hera. And I will reach out to some other people to divide the work.

**Comment by pjpegion** [comment] 2020-03-04 21:26
@ligiabernardet @rsdunlapiv  I have some feedback from a non-developer user.  This person is running on hera, which is a pre-configured machine, and doesn't know what to set UFS_INPUT to.  Since this is a pre-configured machine,  the "fix" files should already be there, so how would a user know what to properly set this but still have the ability to run any date they want (I managed to do this by creating sym links from my UFS_INPUT directory to the fix files), but it is not documented anywhere.

**Comment by llpcarson** [comment] 2020-03-04 21:43
Phil - Good question - here is the placeholder for how to set these envars
on pre-configured platforms.  I don't know if/where the fixed files are
staged on hera, but can update this if that info is available.

Rocky - did you stage this on hera?  Should we stage it somewhere?

https://ufs-mrweather-app.readthedocs.io/en/latest/quickstart.html#setup-the-environment

Laurie

**Comment by jedwards4b** [comment] 2020-03-04 21:45
@pjpegion Also if you want to use the fix files already on the system but stage your own initial condition files you want to change DIN_LOC_IC - that is documented here https://ufs-mrweather-app.readthedocs.io/en/latest/inputs_outputs.html#downloading-and-staging-input-data

**Comment by rsdunlapiv** [comment] 2020-03-04 22:08
@pjpegion and @llpcarson I am using this directory on Hera for `UFS_INPUT`:
`/scratch1/NCEPDEV/stmp2/CIME_UFS`

Should we update the docs to point to that one on Hera?  Maybe the student could test it?

@arunchawla-NOAA it really would be most appropriate for a Hera manager to assign this location.  If no one really cares, then let's just the use the one above.

**Comment by pjpegion** [comment] 2020-03-04 22:33
@rsdunlapiv I passed this info along to my tester, and I will let you know how things progress. Thanks.

**Comment by pjpegion** [comment] 2020-03-05 15:44
@rsdunlapiv My successful runs at C768 were on hera, not cheyenne.

**Comment by arunchawla-NOAA** [comment] 2020-03-07 01:02
@pjpegion is this activity still occurring? Any feedback?

**Comment by MuayScience** [comment] 2020-03-07 01:25
As an FYI, I'm working through the Get Started instructions on Stampede2.

**Comment by pjpegion** [comment] 2020-03-07 17:21
Here was the feedback (note this person was running on hera).
"The directions were great and very clear.  The only problem I had was getting the 
initial conditions, which you helped with."  
The documentation has been updated with the initial condition information.

**Comment by MuayScience** [comment] 2020-03-09 15:39
I ran into a couple of issues that I documented, but I can confirm I was able to run the Dorian test case on Stampede2. :)

**Comment by arunchawla-NOAA** [comment] 2020-03-09 18:09
@ligiabernardet, Can we close this now?

**Closed** 2020-03-09 18:15 UTC
