### ISSUE TITLE
Understanding fv3gfs output files 

### ISSUE THREAD

**Issue by jedwards4b** [ufs-community/ufs-mrweather-app#24] opened 2019-12-10 23:32 UTC
@arunchawla-NOAA @ligiabernardet 

The model as currently configured provides a number of output files, some are configured using the FMS diag_table and others are configured using the model_configure file.   Which of these files should be used to create model baselines for testing?   

The cime baseline mechanism expects a time stamp in the file name and I have added this to diag_table in the past using a documented template like ```atmos_4xdaily.%4yr-%2mo-%2dy-%5s``` However when I try this with fv3gfs the template is not parsed and my output files are incorrectly named ```atmos_4xdaily.%4yr-%2mo-%2dy-%5sc.tile6.nc``` (for each of tile1 - tile6) 

How do we configure the model to properly parse the diag_table and fill in the timestamp in the filenames?  Is there a similar mechanism for model_configure (eg dyn and phys files)?

**Comment by junwang-noaa** [comment] 2019-12-11 01:56
ufs-weather-model uses write grid component to output history files and fms to output GFDL diagnostic fields and restart files. The model_configuration is used to control the history file output frequency and output file names (atmf* and sfc*), the workflow script is using softlink to link real file with names required by operational standards to these atmf and sfcf files. Operationally we only output history files, no atmos_4xdaily file with GFDL diagnostic fields. I personally have not tried the atmos_4xdaily.%4yr-%2mo-%2dy-%5s template for GFDL diagnostic fields. Also I am curious what is the %4yr-%2mo-%2dy-%5s, is it verification time or initial condition time? This atmos_4xdaily files contain outputs from all the output time.

**Comment by jedwards4b** [comment] 2019-12-11 03:16
@junwang-noaa what workflow script are you referring to? 

 It sounds like we should concentrate on the files generated by model_configuration and not worry about the gfdl files except for restarts.  The time stamp is the time of the first record in the file.  The files I see are dyn and phys not atmf and sfcf - are we working with different model_configuration files?

Is there an existing mechanism to put a timestamp in these filenames?

**Comment by climbfuji** [comment] 2019-12-11 03:57
Hi Jim,

dynf and physf files are usually created when quilting is set to .true. in model_configure and the appropriate settings are made. This is from one of the regression tests, in model_configure (just as an example):
```
quilting:                .true.
write_groups:            3
write_tasks_per_group:   4
num_files:               2
filename_base:           'dyn' 'phy'
output_file:             'netcdf'
write_nemsioflip:        .false.
write_fsyncflag:         .false.

# output_grid:             'regional_latlon'
# lon1:                    225.0
# lon2:                    300.0
# lat1:                    10.0
# lat2:                    60.0
# dlon:                    0.2
# dlat:                    0.2

 output_grid:             'rotated_latlon'
 cen_lon:                 -97.5   # central longitude
 cen_lat:                  34.0   # central latitude
 lon1:                    -22.0   # longitude of lower-left point in rotated coordinate system (in degrees)
 lat1:                    -17.0   # latitude of lower-left . . . .
 lon2:                     22.0   # longitude of upper-right . . . .
 lat2:                     17.0   # latitude of upper-right . . . .
 dlon:                      0.2
 dlat:                      0.2

# output_grid:             'lambert_conformal'
# cen_lon:                 -97.5   # central longitude
# cen_lat:                  34.0   # central latitude
# stdlat1:                  30.0
# stdlat2:                  60.0
# nx:                       450     # Number of points along x-axis.
# ny:                       430     # Number of points along y-axis.
# lon1:                    -116.0   # longitude of first grid point (lower-left) (in degrees)
# lat1:                     13.0    # latitude of first grid point (lower-left) (in degrees)
# dx:                       10000.0 # x-direction grid length
# dy:                       10000.0 # y-direction grid length

nfhout:                  3
nfhmax_hf:               12
nfhout_hf:               1
nsout:                   -1
```
I can explain those options to you when we meet tomorrow. The important ones regarding output frequency are `nfhout` (standard output frequency), `nfhmax_hf` and `nfhout_hf` (maximum time for high frequency output, and high frequency output interval), and `nsout` (if set to 1, output at every physics time step). When I use `nfhout` (and optionally `nfhmax_hf` and `nfhout_hf`) I get those files written as `dynf%HHH.nc` and `phyf%HHH.nc`, where `%HHH` stands for the forecast hour (integer only) since initialization - no date. I can't tell you right now if %HHH is always three digits or not (I hope not). If I use `nsout = 1`, I get `dynf%H:%M:%S.nc` (same for phyf), which `%H:%M:%S` being the time since initialization again. For example: `dynf000:07:30.nc` is 7min 30s after init. I am not aware if there is a datetime formatter you can use for the filenames, but I am not an expert.

**Comment by junwang-noaa** [comment] 2019-12-11 04:00
I am talking about operational workflow.

The history file names are defined in model_configure, can be "dyn"/"phy" or "atmf"/"sfcf" (atmf/sfcf is operational GFSv14 output file names, so GFSv15 operational workflow is using same names). But our regression test is using "dyn"/"phy". 
Model put forecast time attached to  the file name (f???). In our operational workflow, we have directory structure and file name
MODEL.YYYYMMDD/$CYCLE/model.t${CYCLE}z.atmf${FH}.nemsio
to specify the time stamp. You can use softlink to point the files to your desired file name.

**Comment by arunchawla-NOAA** [comment] 2019-12-20 16:51
@jedwards4b are there any outstanding issues ? Can we close this ticket now?

**Comment by arunchawla-NOAA** [comment] 2020-01-04 15:41
@jedwards4b @rsdunlapiv Can this ticket be closed now?

**Comment by rsdunlapiv** [comment] 2020-01-09 16:04
@jedwards4b will need to say if he was able to get the output filenames he needs for regression testing.

**Closed** 2020-01-10 22:49 UTC
