### ISSUE TITLE
Error building CCPP file radiation_aerosols.f with cime.

### ISSUE THREAD

**Issue by uturuncoglu** [ufs-community/ufs-mrweather-app#169] opened 2020-08-13 22:41 UTC
@ligiabernardet @climbfuji We are getting following error when we try to build UFS MR Weather App under CIME. I am not sure it is a know issue or not.

```
/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5082: Syntax error, found '==' when expecting one of: <END-OF-STATEMENT> ; <END-OF-FILE>

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5082: Syntax error, found '==' when expecting one of: <END-OF-STATEMENT> ; <END-OF-FILE>

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5082: Syntax error, found '==' when expecting one of: <LABEL> <END-OF-STATEMENT> ; <IDENTIFIER> TYPE MODULE ELEMENTAL IMPURE NON_RECURSIVE ...

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5082: Syntax error, found '==' when expecting one of: <LABEL> <END-OF-STATEMENT> ; <IDENTIFIER> TYPE MODULE ELEMENTAL IMPURE NON_RECURSIVE ...

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5149: Illegal character in statement label field  [=]

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5082: Syntax error, found '==' when expecting one of: <END-OF-STATEMENT> ; <END-OF-FILE>

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5082: Syntax error, found '==' when expecting one of: <END-OF-STATEMENT> ; <END-OF-FILE>

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5082: Syntax error, found '==' when expecting one of: <LABEL> <END-OF-STATEMENT> ; <IDENTIFIER> TYPE MODULE ELEMENTAL IMPURE NON_RECURSIVE ...

/glade/u/home/turuncu/UFS/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(5715): error #5082: Syntax error, found '==' when expecting one of: <LABEL> <END-OF-STATEMENT> ; <IDENTIFIER> TYPE MODULE ELEMENTAL IMPURE NON_RECURSIVE ...
```

In this case, i am using release/public-v1 branch for the model and last commit is

```
commit 8cb21f8a40c8b262bc1b3c0c32f321fdb3244a5c
Author: JulieSchramm <schramm@ucar.edu>
Date:   Wed Jul 15 15:58:23 2020 -0600
```

If you could also create a case on Cheyenne using UFS MR Weather Model  (or I could do it if you provide me the instructions) that could help to compare the possible differences in the build. BTW, I am using intel compiler and MPT combination.

**Comment by climbfuji** [comment] 2020-08-13 22:45
Interesting ...

When I ran the regression tests yesterday for the ufs-weather-model release/public-v1 branch, everything worked on Cheyenne. See https://github.com/ufs-community/ufs-weather-model/pull/186.

Are you using the correct versions of the compiler? This is the modulefile for cheyenne.intel: https://github.com/ufs-community/ufs-weather-model/blob/develop/modulefiles/cheyenne.intel/fv3
```
module load ncarenv/1.3
module load intel/19.1.1
module load mpt/2.19
module load ncarcompilers/0.5.0

##
## use pre-compiled NetCDF, ESMF and NCEP libraries for above compiler / MPI combination
##
module use -a /glade/p/ral/jntp/GMTB/tools/ufs-stack-20200728/intel-19.1.1/mpt-2.19/modules
module load netcdf/4.7.4
module load esmf/8.0.0

module load bacio/2.4.0
module load crtm/2.3.0
module load g2/3.4.0
module load g2tmpl/1.9.0
module load ip/3.3.0
module load nceppost/dceca26
module load nemsio/2.5.1
module load sp/2.3.0
module load w3emc/2.7.0
module load w3nco/2.4.0

module load gfsio/1.4.0
module load sfcio/1.4.0
module load sigio/2.3.0

##
## SIONlib library
##
module use -a /glade/p/ral/jntp/GMTB/tools/modulefiles/intel-19.1.1/mpt-2.19
module load SIONlib/1.7.4

##
## load cmake
##
module load cmake/3.16.4
setenv CMAKE_C_COMPILER mpicc
setenv CMAKE_CXX_COMPILER mpicxx
setenv CMAKE_Fortran_COMPILER mpif90
setenv CMAKE_Platform cheyenne.intel
```

**Comment by uturuncoglu** [comment] 2020-08-14 17:14
@climbfuji CIME is using intel/19.0.5 and mpt/2.19. We did not change anything particular in the build system but it might be nice to check again build options. If you don't mind and if you have, please let me know the run and build directories on Cheyenne and I could use them to compare the configurations.

**Comment by ligiabernardet** [comment] 2020-08-14 17:52
@Ufuk Turuncoglu - NOAA Affiliate <ufuk.turuncoglu@noaa.gov> Dom is on
leave for 10 days.
My understanding is that you need to use this module file for
cheyenne/intel:
https://github.com/ufs-community/ufs-weather-model/blob/release/public-v1/modulefiles/cheyenne.intel/fv3.
Note that this is from the *release/public-v1 *branch. In Dom's last
comment he pointed you to the file from the develop branch (this may or not
work - I don't know).
<https://github.com/ufs-community/ufs-weather-model/blob/release/public-v1/modulefiles/cheyenne.intel/fv3>

In the public/release-v1 branch version of the cheyenne/intel file, you
will see
module use -a /glade/p/ral/jntp/GMTB/tools/modulefiles/intel-19.0.5/mpt-2.19
module load NCEPlibs/1.1.0

It is important to use the NCEPlibs/1.1.0 for the release (has the upgraded
cghres_cube that ingests netCDF), along with the rest of the environment
described in that file.

See if that helps. If not, I'll find some help in DTC to compile/run the
release branch of the ufs-weather-model on Cheyenne for you. Let me know.

**Comment by uturuncoglu** [comment] 2020-08-14 17:55
@ligiabernardet it is fine. I'll try to run the model outside the CIME and find the differences. I'll keep you posted about the progress and if I need any help.

**Comment by uturuncoglu** [comment] 2020-08-17 16:23
@ligiabernardet I just wonder that how can i clean existing build?

**Comment by ligiabernardet** [comment] 2020-08-17 17:41
@Laurie Carson <carson@ucar.edu> Can you help answer this question?

**Comment by uturuncoglu** [comment] 2020-08-17 20:16
@climbfuji @ligiabernardet it seems that the error is gone whan I update the model to the latest. I am still testing it and I'll double check.

**Comment by panll** [comment] 2020-08-17 20:32
Hi, ufuk, 
you can use following command to do the compiling under the test directory :
./compile_cmake.sh $PWD/.. cheyenne.intel 'CCPP=Y' Yes Yes

the option "Yes" is to set the clean up before and after the build.

@uturuncoglu

**Comment by uturuncoglu** [comment] 2020-08-17 22:13
Okay. Thanks @panll.

**Comment by uturuncoglu** [comment] 2020-08-19 20:55
Hi all, it seems that I was wrong and I am getting same error with updated code. If I try to create a new case and try to do a fresh build, it fails with 

`Building atm with output to /glade/scratch/turuncu/ufs-mrweather-app-workflow.c96v2/bld/atm.bldlog.200819-142748
/glade/scratch/turuncu/ufs-mrweather-app-workflow.c96v2/bld/atm/obj/FV3/ccpp/physics/physics/radiation_aerosols.f(4840): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: )` 

error but if I run ./case.build again. It compiles without any problem. I also try to find any possible difference but I could not fina one that could case the issue. Any suggestion? @climbfuji @ligiabernardet

**Comment by ligiabernardet** [comment] 2020-08-19 21:02
Hi Ufuk, Unfortunately I do not know what could be causing this problem. My
understanding is that the model is building fineas a standalone (outside of
CIME). Have you built the model as standalone successfully? - if so, then
you could look at any differences. If you need DTC to build it on Cheyenne
for you, let me know.

**Comment by uturuncoglu** [comment] 2020-08-19 21:10
Yes, I could build standalone model outside of CIME without any problem. @jedwards4b is also looking for the possible differences now.

**Comment by ligiabernardet** [comment] 2020-08-24 16:26
@climbfuji Do you have any idea what can cause this problem that Jim and Ufuk reported? They cannot compile the code, but at a second attempt it works. Linlin and I were not able to reproduce the problem using the updated CIME on Hera or Cheyenne.

**Comment by climbfuji** [comment] 2020-08-24 16:28
Not sure. Maybe some default libraries loaded in the user environment? Always a bad idea. We usually do "module purge" before we build anything.

**Comment by uturuncoglu** [comment] 2020-08-24 16:34
@climbfuji module purge also exist in the CIME interface. I also compared that specific source file with old version of model that was used in 1.0 and it seems that source file is same and did not change since last release. It is strange but it gives error sometimes.

**Comment by climbfuji** [comment] 2020-08-24 16:40
Can I check out the latest version using branch release/public-v1 of the ufs-mrweather-app and then use the manage externals utility?

**Comment by uturuncoglu** [comment] 2020-08-24 16:57
@climbfuji yes you could test it with latest version of app but you need to use ufs_fix branch for CIME. This will be merged with CIME later. Here is the instructions to test,

```
export UFS_DRIVER=nems
git clone https://github.com/ufs-community/ufs-mrweather-app.git
cd ufs-mrweather-app
git checkout ufs-release-v1.1
./manage_externals/checkout_externals
cd cime/scripts
git checkout ups_fix
CIME_MODEL=ufs ./create_newcase --compset GFSv15p2 --res C96 --case ufs-mrweather-app-workflow.c96 --workflow ufs-mrweather
cd ufs-mrweather-app-workflow.c96
./case.setup
NOTE:  add input_type = "gaussian_netcdf" to user_nl_ufsatm
./xmlchange RUN_STARTDATE=2020-02-02
./xmlchange DOUT_S=FALSE
./xmlchange STOP_OPTION=nhours
./xmlchange STOP_N=36
./xmlchange JOB_WALLCLOCK_TIME=00:30:00
./xmlchange USER_REQUESTED_WALLTIME=00:30:00
./case.build
./case.submit
```

**Comment by uturuncoglu** [comment] 2020-08-24 16:59
BTW, currently I am running full CIME test suite again. I also did it at the weekend and only two test failed with the compile error even with sequential build (make -j 1). So, the error is not consistent.

```
  SMS_Lh3_D.C192.GFSv16beta.cheyenne_intel (Overall: FAIL) details:
    FAIL SMS_Lh3_D.C192.GFSv16beta.cheyenne_intel MODEL_BUILD time=75
  SMS_Lh3_D.C96.GFSv16beta.cheyenne_intel (Overall: FAIL) details:
    FAIL SMS_Lh3_D.C96.GFSv16beta.cheyenne_intel MODEL_BUILD time=75
```

**Comment by climbfuji** [comment] 2020-08-24 19:48
Don't think it matters but are you using tcsh or bash on cheyenne?

**Comment by uturuncoglu** [comment] 2020-08-24 19:53
I am using BASH shell.

**Comment by climbfuji** [comment] 2020-08-24 19:59
As a first step, I just built the model as follows:
```
git clone https://github.com/ufs-community/ufs-mrweather-app.git
cd ufs-mrweather-app
git checkout ufs-release-v1.1
./manage_externals/checkout_externals
cd src/model
export CMAKE_Platform=cheyenne.gnu # or cheyenne.intel
module use -a $PWD/modulefiles/cheyenne.gnu # or cheyenne.intel
module load fv3
./build.sh 2>&1 | tee build.log
```
This worked for both Intel and GNU. I will now try checking out the ups_fix CIME branch and build the model through CIME.

**Comment by climbfuji** [comment] 2020-08-24 20:49
Ok, here is what I did:
```
UFS_SCRATCH=$PWD/ufs_scratch PROJECT=P48503002 CIME_MODEL=ufs ./cime/scripts/create_newcase --compset GFSv15p2 --res C96 --case ufs-mrweather-app-workflow.c96 --workflow ufs-mrweather
cd ufs-mrweather-app-workflow.c96
./case.setup
export UFS_INPUT=/glade/work/heinzell/fv3/ufs-mrweather-app/ufs-mrweather-app-20200824/ufs_input
mkdir -p /glade/work/heinzell/fv3/ufs-mrweather-app/ufs-mrweather-app-20200824/ufs_input/ufs_inputdata
./case.setup
./preview_run
vi user_nl_ufsatm # add input_type = "gaussian_netcdf"
./xmlchange RUN_STARTDATE=2020-02-02
./xmlchange DOUT_S=FALSE
./xmlchange STOP_OPTION=nhours
./xmlchange STOP_N=36
./xmlchange JOB_WALLCLOCK_TIME=00:30:00
./xmlchange USER_REQUESTED_WALLTIME=00:30:00
./case.build
```
This worked for both Intel and GNU.

**Comment by uturuncoglu** [comment] 2020-08-24 20:51
@climbfuji Okay. Strange. I am not sure what we will do with this. I'll try to use app v1.0 to see same error in there or not.

**Comment by climbfuji** [comment] 2020-08-24 21:04
> @climbfuji Okay. Strange. I am not sure what we will do with this. I'll try to use app v1.0 to see same error in there or not.

In https://github.com/ufs-community/ufs-mrweather-app/issues/169#issuecomment-678485639 you are running the build on a compute node using qcmd. Are you always doing that? I think @ligiabernardet, @panll and myself compiled on the login node.

**Comment by uturuncoglu** [comment] 2020-08-24 21:30
@climbfuji No. I tested both of them. To run the test suite, i am using compute node but creating standalone new case I am using login node.

**Comment by uturuncoglu** [comment] 2020-08-25 22:06
@ligiabernardet @climbfuji we are trying to update CIME to use model's internal module files. So, I tried to update the model (release/public-v1) but I could not see the Orion module files. It seems it is exist in develop,

https://github.com/ufs-community/ufs-weather-model/blob/develop/modulefiles/orion.intel/fv3

is there any plan to bring Orion module file to release/public-v1 branch?

**Comment by ligiabernardet** [comment] 2020-08-27 03:29
@uturuncoglu I talked to @climbfuji who let me know that most modules (apart from Hera and Cheyenne) in the release/public-v1 are not up to date because the App was not previously using those. He said he'd update those modules soon.

**Comment by uturuncoglu** [comment] 2020-08-27 19:18
@ligiabernardet That is great. Please let me know when it is ready.

**Comment by climbfuji** [comment] 2020-08-28 13:17
The PRs is here: https://github.com/ufs-community/ufs-weather-model/pull/192 - we should be able to merge this today.

**Comment by climbfuji** [comment] 2020-08-28 13:18
Why is this issue called "Error building CCPP" - this is not a CCPP error.

**Comment by ligiabernardet** [comment] 2020-08-28 14:53
It is historical - that is what was believed at the time. I will change the
subject.

**Comment by uturuncoglu** [comment] 2020-08-28 15:22
@climbfuji Thanks.

**Comment by climbfuji** [comment] 2020-08-28 16:26
See the following PRs: https://github.com/NOAA-EMC/NCEPLIBS-external/pull/67 https://github.com/ufs-community/ufs-weather-model/pull/192

**Comment by climbfuji** [comment] 2020-08-28 19:00
All these PRs were merged, should be ready to test.

**Comment by climbfuji** [comment] 2020-08-28 19:02
And I can confirm that `ncep_post` no longer depends on libsz on hera and jet (these were the only "bad" machines).

**Comment by uturuncoglu** [comment] 2020-08-28 19:44
@climbfuji okay, i am updating the app. I'll let you know when it is ready

**Comment by uturuncoglu** [comment] 2020-08-28 21:14
@climbfuji @ligiabernardet @fossell @hertneky Here is the instruction to test the updated app. I tested on Cheyenne and it seems working

export UFS_DRIVER=nems
git clone https://github.com/ufs-community/ufs-mrweather-app.git
cd ufs-mrweather-app
git checkout ufs-release-v1.1
./manage_externals/checkout_externals 
cd cime/scripts/
./create_newcase --compset GFSv15p2 --res C96 --case ufs-mrweather-app-workflow.c96 --workflow ufs-mrweather
cd ufs-mrweather-app-workflow.c96/
./case.setup
./case.build
./xmlchange DOUT_S=FALSE
./xmlchange STOP_OPTION=nhours
./xmlchange STOP_N=36
./xmlchange JOB_WALLCLOCK_TIME=00:30:00
./xmlchange USER_REQUESTED_WALLTIME=00:30:00
./case.submit

BTW, my first build attempt failed with same way and if you want to look at the build log, it is in `/glade/scratch/turuncu/ufs-mrweather-app-workflow.c96/bld/atm.bldlog.200828-141511`. I also check the radiation_aerosols.f file but i could not see any problem with it. It is very strange. The second ./case.build works fine as expected.

**Notes:** 
1. if you need to use custom post flat files, you need to put them into SourceMods/src.ufsatm using same naming convention.

2. Do not forget the change the name of the default input file (it is under icfiles/201908/20190829) as atm.input.ic.grb2. Since we change the file naming convention, all the files must follow the following convention.

  * NEMSIO - atm.input.ic.nemsio and sfc.input.ic.nemsio
  * GRIB2 - atm.input.ic.grb2
  * NETCDF - atm.input.ic.nc and sfc.input.ic.nc

**Comment by hertneky** [comment] 2020-08-28 22:07
@uturuncoglu Under notes #2. I don't see any files existing in icfiles/201908/20190829. Am I missing something?

**Comment by uturuncoglu** [comment] 2020-08-28 22:13
@hertneky it must be in $UFS_INPUTDATA/ufs_inputdata/icfiles/201908/20190829. If you are trying on Cheyyene it must work fine but for other platforms you need to copy the file from following FTP link. 

https://ftp.emc.ncep.noaa.gov/EIB/UFS/inputdata/201908/20190829/

This just for IC and other files will be downloaded automatically. ,

BTW, i defined following variables on Orion.

export WORK=/work/noaa/nems/tufuk
export UFS_INPUT=$WORK
export UFS_INPUTDATA=$WORK
export UFS_SCRATCH=$WORK

**Comment by hertneky** [comment] 2020-08-28 22:21
@uturuncoglu I am running on Cheyenne. What should $UFS_INPUT be on Cheyenne? For v1.0, I did setenv $UFS_INPUT $CESMDATAROOT -> giving a full path of /glade/p/cesmdata/cseg/ufs_inputdata/icfiles/201908/20190829, which does not contain any files. Does $UFS_INPUT need to be changed to point somewhere else.

**Comment by uturuncoglu** [comment] 2020-08-28 22:24
@hertneky sorry, i moved them for testing and I forgot it. could you try again. sorry again.

**Comment by hertneky** [comment] 2020-08-28 22:43
@uturuncoglu that works now - thanks

**Comment by hertneky** [comment] 2020-08-28 23:11
@uturuncoglu Testing flat file customization complete and working as visualized/intended for updated v1.1 on Cheyenne. See #174 for details.

**Comment by uturuncoglu** [comment] 2020-09-08 21:33
@ligiabernardet @climbfuji 
I am getting `        /work/noaa/nems/tufuk/scratch/SMS_Lh3.C96.GFSv15p2.orion_intel.20200908_163017_0550g2/bld/atm/obj/FV3/ccpp/physics/physics/radiation_aerosols.f(2197): error #5082: Syntax error, found '-' when expecting one of: <LABEL> <END-OF-STATEMENT> ; <IDENTIFIER> TYPE MODULE ELEMENTAL IMPURE NON_RECURSIVE ...` type errors also on Orion.

**Comment by climbfuji** [comment] 2020-09-08 21:42
@uturuncoglu how exactly are you getting the code onto orion (and cheyenne)?

**Comment by uturuncoglu** [comment] 2020-09-08 21:43
@climbfuji i am just using manage externals. Most of the test cases are failing with build error.

**Comment by uturuncoglu** [comment] 2020-09-08 21:46
@climbfuji For example following test failed with build error,
`/work/noaa/nems/tufuk/scratch/SMS_Lh3_D.C96.GFSv16beta.orion_intel.20200908_163017_0550g2` and the log is in here `/work/noaa/nems/tufuk/scratch/SMS_Lh3_D.C96.GFSv16beta.orion_intel.20200908_163017_0550g2/bld/atm.bldlog.200908-163714`.

**Comment by uturuncoglu** [comment] 2020-09-08 22:14
@climbfuji FYI, only 6/19 tests are PASSED and others are failed with build error on Orion.

**Comment by uturuncoglu** [comment] 2020-09-09 15:57
@climbfuji I compared application versions 1.0 and the 1.1 to find any difference in the compile options for the radiation_aerosols.f file and both of them are compiled exactly same options. Also, I run full test suite with 1.0 also and I did not see any compile time error. The CHGRES is also failing for some cases in 1.0, which was working in the 1.0 release time (https://github.com/ufs-community/ufs-mrweather-app/issues/179). This indicates some changes in the system level. At this point the only difference seems model versions. I'll also compare the buildlib between 1.0 and 1.1 to find any particular reason that could cause the build error.

**Comment by climbfuji** [comment] 2020-09-09 16:00
> @climbfuji I compared application versions 1.0 and the 1.1 to find any difference in the compile options for the radiation_aerosols.f file and both of them are compiled exactly same options. Also, I run full test suite with 1.0 also and I did not see any compile time error. The CHGRES is also failing for some cases in 1.0, which was working in the 1.0 release time (#179). This indicates some changes in the system level. At this point the only difference seems model versions. I'll also compare the buildlib between 1.0 and 1.1 to find any particular reason that could cause the build error.

I do get the build error as well when I use the CIME regression tests. The changes in the model code itself between 1.0 and 1.1 are tiny and have nothing to do with actual source code (Python 3 support for the CCPP code generator, changes in namelist templates). This smells a lot like some changes in CIME causing the compilation to fail.

**Comment by uturuncoglu** [comment] 2020-09-09 16:05
@climbfuji Okay that is fine. I am looking into CIME to find anything. I'll try to test the build by setting GMAKE_J=1 with xmlchange. The default value is 8. To see, I could reproduce the issue also with GMAKE_J=1.

**Comment by ligiabernardet** [comment] 2020-09-22 16:44
This problem stopped happening after @uturuncoglu reverted to the MRW 1.0 buildlib.

**Closed by ligiabernardet** 2020-09-22 16:44 UTC
Labels: bug
