### ISSUE TITLE
Doc issue reported by first student tester

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#95] opened 2020-02-22 22:47 UTC
From the first GST response - this is in the WM UG:
"I encountered a problem when I directly copied and paste the following command, export CCPP_SUITES=’FV3_GFS_v15p2,FV3_GFS_v16beta’, in the page of Compiling the Code without an Application. I have to manually modify the quotation mark again to aviod the parsing error in python. I used the terminal application in Mac OS."

**Comment by climbfuji** [comment] 2020-02-26 15:59
I will leave this to the documentation pros to fix.

**Comment by JulieSchramm** [comment] 2020-02-26 16:58
export CCPP_SUITES=’FV3_GFS_v15p2,FV3_GFS_v16beta’ works from the command line for

laramie/cheyenne bash
laramie/cheyenne csh (setenv CCPP_SUITES ’FV3_GFS_v15p2,FV3_GFS_v16beta’)
MacOS bash
Hera tcsh (setenv CCPP_SUITES ’FV3_GFS_v15p2,FV3_GFS_v16beta’)

Where is the python being used?

**Comment by ceceliadid** [comment] 2020-02-26 17:17
I don't know, I just asked her offline. It works fine as cut and paste for me.

**Comment by ceceliadid** [comment] 2020-02-27 17:56
This is what she said -

The build.sh would execute the following python code
./FV3/ccpp/framework/scripts/ccpp_prebuild.py
it uses this flag
--suites=${CCPP_SUITES}
I think in the python code it tends to parse the CCPP_SUITES for what suite to be compiled.
If the environment variable has the unrecognized punctuation, I guess python would encounter problem to read it.
That’s what I think.

Thanks,
Shih-Wei

**Comment by ligiabernardet** [comment] 2020-03-03 17:27
Since none of us could reproduce this error, I am not sure how to fix it.

**Comment by ligiabernardet** [comment] 2020-03-05 16:38
@climbfuji Do you have any advice on how to address this problem reported by the user?

**Comment by arunchawla-NOAA** [comment] 2020-03-06 22:56
this may be some strange way her environment is set up. I do not know if there is any action item here. If the student is no longer engaged can we close this in anticipation that we will have more engagement from other students? This for @ceceliadid and @ligiabernardet

**Comment by ceceliadid** [comment] 2020-03-06 23:23
Yeah, I don't know. I think it's fine to close it.

**Comment by climbfuji** [comment] 2020-03-06 23:24
I concur.

**Closed** 2020-03-06 23:26 UTC
