### ISSUE TITLE
fv3atm ufs_public_release branch needs to reflect latest CCPP release number

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#45] opened 2019-12-20 23:49 UTC
A non-answer-changing fix needs to be applied to two files:
https://github.com/NOAA-EMC/fv3atm/blob/ufs_public_release/ccpp/suites/suite_FV3_GFS_v15p2.xml
and
https://github.com/NOAA-EMC/fv3atm/blob/ufs_public_release/ccpp/suites/suite_FV3_GFS_v16beta.xml
to reflect the number of the public release (v4)
ver="3" needs to become ver="4"

**Comment by climbfuji** [comment] 2019-12-21 00:07
While we are going to disable the dynamic CCPP build for the release, we should also update the version numbers in the various scripts in ufs-weather-model at the same time.

**Comment by junwang-noaa** [comment] 2019-12-23 18:12
Dom,

Do you have the changes ready? Would you please create a pull request to ufs-weather-model ufs_public_release branch for this issue? We can start the commit process then.

**Comment by climbfuji** [comment] 2019-12-23 18:24
No, I haven't done that yet. I can create the branch and include the removal of the inline post if you think this makes sense?

**Comment by junwang-noaa** [comment] 2019-12-23 20:16
Dom,

I am talking about the issue Ligia created: changing ccpp version number in the two GFS suite files. I am not sure how inline post will be related to this issue, my understanding is that the public release will be build with "NO_INLINE_POST", we don't need to remove is from the source code.

**Comment by climbfuji** [comment] 2019-12-23 20:23
The build team had a discussion about this today (and Arun was on the call, too) and from our point of view we should remove the inline post code. I can live with both options, but I am in favor of removing it for the public release. @arunchawla-NOAA @GeorgeGayno-NOAA

**Comment by junwang-noaa** [comment] 2019-12-23 21:02
Dom,

I talked to Arun. He agrees that we do not need change source code for
inline post. I do not know what are the issues with building the public
release compile the code, especially you knew we can compile "
NO_INLINE_POST" as a compile option. With that, you do not need POST
library and g2tmpl. Since the public release do not run with WW3, you do
not need the following lib either :

module load g2/3.1.1
module load crtm/2.2.6
module load jasper/1.900.1
module load png/1.2.44
module load z/1.2.11

Only nceplibs; bacio, nemsio, ip, sp, w3emc,w3nco. Please do not change
source code as much as possible, I am worried that the next step some
one may come up to remove WW3, old gfs physics, write grid comp, etc. Since
we promise to bring the changes to public back to develop branch,  I hope
to keep the source code untouched, as we did for GSD physics in CCPP.
Thanks and please let me know if you have any questions. Thanks

Jun

**Comment by climbfuji** [comment] 2019-12-23 21:05
That's totally fine with me. In this case I suggest to add the -DNO_INLINE_POST option to all configuration files for all platforms. But please talk with @GeorgeGayno-NOAA to make sure that the three of you are on the same page. Thank you!

**Comment by arunchawla-NOAA** [comment] 2019-12-23 21:07
I think you meant George Vandenberghe
---------------------------------------------------------------
Arun Chawla
Chief
Engineering & Implementation Branch
Room 2083
National Center for Weather & Climate Prediction
5830 University Research Court
College Park, MD 20740
Ph: 301-683-3740
Fx: 301-683-3703
------------------------------------------------------------

**Comment by climbfuji** [comment] 2019-12-23 21:08
Regarding the NCEPlibs: I think that the pre and post utilities (UFS_UTILS: chgres_cube, NCEPlibs-post: standalone post) require more than the libraries you listed (I know that the ones you listed are required for the ufs-weather-model). The NCEPlibs umbrella build will take care of this. But you are correct in that we should remove the module load statements from the ufs-weather-model configuration files .

**Comment by climbfuji** [comment] 2019-12-23 21:09
@arunchawla-NOAA Oh yes! I am sorry. This @username-autocomplete service is letting me down. Apologies to both Georges for messing this up.

**Comment by arunchawla-NOAA** [comment] 2020-01-06 19:50
@junwang-noaa can we close this ticket?

**Comment by junwang-noaa** [comment] 2020-01-06 20:25
Dom,

So we can disable the dynamic CCPP build by using the -DNO-INLINE_POST. Now let's go back to the original request Ligia posted, do you have the CCPP  code change ready that updates CCPP version from 3 to 4 in ufs-weather-model public release branch? Thanks.

Jun

**Comment by ligiabernardet** [comment] 2020-01-06 20:39
Hi Jun and Dom, pls also note we are nearly done with the
Scientific Documentation updates and will propose those for commit soon to
ccpp-physics. Ligia

**Comment by climbfuji** [comment] 2020-01-06 20:44
I am almost finished with the v3 to v4 update, this will include the bug fixes for the two regression tests v15p2 and v16 (those were crashing in DEBUG mode) and for the failure to detect them.

**Comment by arunchawla-NOAA** [comment] 2020-01-09 16:21
what is the status of this ? @climbfuji

**Comment by climbfuji** [comment] 2020-01-09 16:55
This needs to be merged first: https://github.com/ufs-community/ufs-weather-model/pull/22, then I need to update my PRs (https://github.com/ufs-community/ufs-weather-model/pull/25). Once this is in, we can merge the scidoc update (https://github.com/NCAR/ccpp-physics/pull/376).

**Comment by arunchawla-NOAA** [comment] 2020-01-15 01:19
@climbfuji looks like @DusanJovic-NOAA has merged the two ufs-weather-model PRs. Are we close to closing this ticket?

**Comment by climbfuji** [comment] 2020-01-15 01:34
Yes, because my PR #25 contained the scidoc update. Will close.

**Closed by climbfuji** 2020-01-15 01:34 UTC
