### ISSUE TITLE
CIME update for pre-configured machines with module changes (including Orion)

### ISSUE THREAD

**Issue by jedwards4b** [ufs-community/ufs-mrweather-app#155] opened 2020-06-26 14:38 UTC
Recent system changes on Orion require an update to the modules section of config_machines.xml in cime

**Comment by arunchawla-NOAA** [comment] 2020-08-10 15:05
@rsdunlapiv who would you assign to do and test this ?

**Comment by jedwards4b** [comment] 2020-08-10 15:16
@arunchawla-NOAA I will do it.  I was waiting for all the pieces to be updated first.

**Comment by rsdunlapiv** [comment] 2020-08-14 18:15
This applies to all pre-configured platforms.  This needs to be confirmed before the release.

**Comment by rsdunlapiv** [comment] 2020-08-14 18:42
CIME should be referencing the precofnigured machine modulefiles than @climbfuji is setting up for each platform, e.g.:
`https://github.com/ufs-community/ufs-weather-model/blob/release/public-v1/modulefiles/hera.intel/fv3`

**Comment by rsdunlapiv** [comment] 2020-08-14 19:35
@jedwards4b and @uturuncoglu - is there any reason not to reference the modulefiles that @climbfuji has set up for each preconfigured platform within the config_machines.xml for each machine?  
`https://github.com/ufs-community/ufs-weather-model/blob/release/public-v1/modulefiles`
It seems that if we do this, we would never have to update `config_machines.xml` moving forwards as it would stay up to date with the ufs-weather-model modulefiles.

**Comment by uturuncoglu** [comment] 2020-08-14 19:45
@rsdunlapiv actually we were pointing @climbfuji NCEPLIBS installation for release. I think that the modules files were also same but I am not fully sure about that and needs @jedwards4b input. 

BTW, this could be little bit problematic for us in the future because UFS HAFS application will need newer version of ESMF (>8.1.0 beta snapshot 24) . Currently, we are not supporting Intel+IntelMPI combination for UFS MR Weather app and we are pointing our newer ESMF installation for Intel+IntelMPI for HAFS app. This works in the current implementation. When we support also GNU and MPT for HAFS application we need to find a way to point different modules and ESMF installations for different UFS applications unless they are unified.

**Comment by arunchawla-NOAA** [comment] 2020-08-14 19:54
If you use the module files with the model repositories then that should take care of it. In any case when the final release of esmf 8.1.0 comes out then we do update all our models to that.

**Comment by rsdunlapiv** [comment] 2020-08-14 19:56
@uturuncoglu Does pointing to the NCEPLIBS installation include *all* modules, such as the compiler and mpi?  I didn't think so - so it seems we are duplicating that information in the CIME config_machines.xml.  This is why I am advocating using the modulefiles inside the ufs-weather-model repository.  

Regarding different versions of ESMF (and other libs) - there is a very high likelihood that different applications will need to point to different library versions, especially since some applications are in development while others are being released.  So in this way we cannot depend on a machine determining which libs to use - that seems to be based on a combination of machine and the application itself.  Is there a way to handle this inside CIME?

**Comment by uturuncoglu** [comment] 2020-08-14 20:06
@rsdunlapiv not it just point ESMF, model related libraries and tools that are used for pre- and post-processing. The CIME also looks to environment variables that are defined by NCEPLIBS provided special script (setenv_nceplibs.sh, needs to be source before run). The rest of the module files need to be define in the machine.xml file and needs to be consistent with NCEPLIBS installation.

I am not sure how we handle  different versions of compilers and library installations for different UFS applications. We need to discuss it with @jedwards4b.

**Comment by arunchawla-NOAA** [comment] 2020-08-14 20:06
these modules have to be determined at the model build level and the information is provided there. CIME should just use that

**Comment by uturuncoglu** [comment] 2020-08-14 20:14
@arunchawla-NOAA even if we use build level information (modules, compiler options etc.) coming from model itself, I think we have to map some of those build variables to CIME internal ones. Currently we are using configure_cime.cmake file in the UFSATM interface to map CIME internal compiler flags to model's one. If we need to support different combinations and configurations for each app then we need to revisit this part of implementation and it requires additional time to implement and design. Again, I am not fully expert of CIME build system and @jedwards4b could give more information about it or correct me if I am wrong.

**Comment by rsdunlapiv** [comment] 2020-08-14 21:11
@uturuncoglu to keep things as simple as possible for this specific release, is the only dependency requiring the updated ESMF library CDEPS?  Since CDEPS is not used in the release, can it be removed as a dependency?

If we need application-based config_machine.xml files, should we introduce separate CIME_MODEL directories - so instead of only "UFS" we would have UFS_MR, UFS_HAFS, and UFS_S2S?

**Comment by uturuncoglu** [comment] 2020-08-14 21:40
@rsdunlapiv Currently we implemented a way to get rid of CDEPS dependency by setting an environment variable. Yes, having different config directories under CIME for each UFS application could simplify the implementation but it also results lots of duplications and supporting of those applications could be problematic in the future.

**Comment by ligiabernardet** [comment] 2020-09-01 02:32
This work is complete and if any problems arise we'll open a new issue.

**Closed by ligiabernardet** 2020-09-01 02:32 UTC
Labels: release-1.1
